import httpx
import logging
from typing import Optional
from app.core.config import settings

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"


class GitHubService:
    def __init__(self):
        self.token = settings.GITHUB_APP_TOKEN
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    async def post_pr_comment(self, repo_full_name: str, pr_number: int, analysis: dict, run_id: str) -> bool:
        """Post AI analysis as a review comment on a PR."""
        confidence = analysis.get("confidence_score", 0)
        confidence_pct = int(confidence * 100)
        confidence_emoji = "🟢" if confidence >= 0.8 else "🟡" if confidence >= 0.5 else "🔴"
        category = analysis.get("root_cause_category", "unknown").replace("_", " ").title()

        fix_snippet = ""
        if analysis.get("fix_code_snippet"):
            fix_snippet = f"\n\n**💻 Fix:**\n```\n{analysis['fix_code_snippet']}\n```"

        body = f"""## 🤖 OpsAI Analysis {confidence_emoji} {confidence_pct}% confidence

**Root Cause Category:** `{category}`

**Summary:** {analysis.get('root_cause_summary', 'No summary available.')}

**Error Snippet:**
```
{analysis.get('error_snippet', 'N/A')}
```

**💡 Fix Suggestion:** {analysis.get('fix_suggestion', 'No suggestion available.')}{fix_snippet}

---
*[View full analysis on OpsAI →]({settings.ALLOWED_ORIGINS[0] if settings.ALLOWED_ORIGINS else 'https://opsai.app'}/runs/{run_id})*"""

        url = f"{GITHUB_API}/repos/{repo_full_name}/issues/{pr_number}/comments"
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json={"body": body}, headers=self.headers)
            if resp.status_code == 201:
                logger.info(f"Posted PR comment on {repo_full_name}#{pr_number}")
                return True
            logger.error(f"Failed to post PR comment: {resp.status_code} {resp.text}")
            return False

    async def create_fix_pr(self, repo_full_name: str, base_branch: str, analysis: dict, run_id: str) -> Optional[str]:
        """Create an auto-fix branch and PR if applicable."""
        fix_snippet = analysis.get("fix_code_snippet")
        if not fix_snippet:
            logger.info("No fix snippet available, skipping auto-fix PR.")
            return None

        category = analysis.get("root_cause_category", "unknown")
        fix_branch = f"opsai/autofix-{category}-{run_id[:8]}"

        # Get base branch SHA
        async with httpx.AsyncClient() as client:
            ref_resp = await client.get(
                f"{GITHUB_API}/repos/{repo_full_name}/git/ref/heads/{base_branch}",
                headers=self.headers
            )
            if ref_resp.status_code != 200:
                logger.error(f"Could not get ref for {base_branch}")
                return None
            base_sha = ref_resp.json()["object"]["sha"]

            # Create fix branch
            branch_resp = await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/git/refs",
                json={"ref": f"refs/heads/{fix_branch}", "sha": base_sha},
                headers=self.headers
            )
            if branch_resp.status_code not in (201, 422):
                logger.error(f"Could not create branch: {branch_resp.text}")
                return None

            # Create PR
            pr_body = f"""## 🤖 OpsAI Auto-Fix

This PR was automatically generated by OpsAI based on CI failure analysis.

**Root Cause:** {analysis.get('root_cause_summary', 'N/A')}

**Suggested Fix:**
```
{fix_snippet}
```

**Confidence Score:** {int(analysis.get('confidence_score', 0) * 100)}%

> ⚠️ Please review this fix carefully before merging. Auto-fixes are best-effort suggestions.

[View full analysis →]({settings.ALLOWED_ORIGINS[0] if settings.ALLOWED_ORIGINS else 'https://opsai.app'}/runs/{run_id})"""

            pr_resp = await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/pulls",
                json={
                    "title": f"🤖 [OpsAI] Auto-fix: {category.replace('_', ' ').title()} issue",
                    "body": pr_body,
                    "head": fix_branch,
                    "base": base_branch,
                },
                headers=self.headers
            )
            if pr_resp.status_code == 201:
                pr_url = pr_resp.json()["html_url"]
                logger.info(f"Created auto-fix PR: {pr_url}")
                return pr_url
            logger.error(f"Could not create PR: {pr_resp.text}")
            return None


github_service = GitHubService()
